version: '3.4'

services:
  kilo2api:
    image: deanxv/kilo2api:latest
    container_name: kilo2api
    restart: always
    ports:
      - "7033:7033"
    volumes:
      - ./data:/app/kilo2api/data
    environment:
      - KL_COOKIE=******  # cookie (多个请以,分隔)
      - API_SECRET=123456  # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔)
      - TZ=Asia/Shanghai